reportPhoto(title, username, photoId) ::= <<
<head>
</head>
<body>
<div style="width:100%!important;background-color:#ececec;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;font-family:Helvetica Neue,Arial,Helvetica,Geneva,sans-serif">
<table width="100%" cellpadding="0" cellspacing="0" border="0" style="background-color:#ececec">
	<tbody><tr style="border-collapse:collapse">
		<td align="center" bgcolor="#ececec" style="border-collapse:collapse">
        	<table width="640" cellpadding="0" cellspacing="0" border="0">
            	<tbody><tr style="border-collapse:collapse"><td width="640" height="20" style="border-collapse:collapse"></td></tr>
                
            	<tr style="border-collapse:collapse">
                	<td width="640" style="border-collapse:collapse">
                        <table width="640" cellpadding="0" cellspacing="0" border="0" bgcolor="#425470" style="border-radius:6px 6px 0px 0px;background-color:#556c90;color:#d9fffd">
    <tbody><tr style="border-collapse:collapse">
        <td width="15" style="border-collapse:collapse"></td>
        <td width="350" valign="middle" align="left" style="border-collapse:collapse">
            <table width="350" cellpadding="0" cellspacing="0" border="0">
                <tbody><tr style="border-collapse:collapse"><td width="350" height="8" style="border-collapse:collapse"></td></tr>
            </tbody></table>
            <div style="font-size:12px;color:#d9fffd"><a href="http://mdiss.createsend3.com/t/j-e-ftjihl-l-n/" style="font-weight:bold;color:#d9fffd;text-decoration:none" target="_blank">Web version</a><span>&nbsp;&nbsp;|&nbsp; <a href="http://mdiss.updatemyprofile.com/j-l-2AD73FFF-l-p" style="font-weight:bold;color:#d9fffd;text-decoration:none" target="_blank">Update preferences</a>&nbsp;&nbsp;|&nbsp; <a href="http://mdiss.createsend3.com/t/j-u-ftjihl-l-x/" style="font-weight:bold;color:#d9fffd;text-decoration:none" target="_blank">Unsubscribe</a></span></div>
            <table width="350" cellpadding="0" cellspacing="0" border="0">
                <tbody><tr style="border-collapse:collapse"><td width="350" height="8" style="border-collapse:collapse"></td></tr>
            </tbody></table>
        </td>
        <td width="30" style="border-collapse:collapse"></td>
        <td width="255" valign="middle" align="right" style="border-collapse:collapse">
            <table width="255" cellpadding="0" cellspacing="0" border="0">
                <tbody><tr style="border-collapse:collapse"><td width="255" height="8" style="border-collapse:collapse"></td></tr>
            </tbody></table>
            <table cellpadding="0" cellspacing="0" border="0">
    <tbody><tr style="border-collapse:collapse">
        
        <td valign="middle" style="border-collapse:collapse"><a href="http://mdiss.createsend3.com/t/j-fb-ftjihl-l-m/" rel="cs_facebox" style="font-weight:bold;color:#d9fffd;text-decoration:none" target="_blank"><img src="https://img.createsend1.com/img/templatebuilder/like-glyph.png" border="0" width="8" height="14" alt="Facebook icon" style="min-height:auto;line-height:100%;outline-style:none;text-decoration:none;display:block"></a></td>
        <td width="3" style="border-collapse:collapse"></td>
        <td valign="middle" style="border-collapse:collapse"><div style="font-size:12px;color:#d9fffd"><a href="http://mdiss.createsend3.com/t/j-fb-ftjihl-l-c/" rel="cs_facebox" style="font-weight:bold;color:#d9fffd;text-decoration:none" target="_blank">Like</a></div></td>
        
        
        <td width="10" style="border-collapse:collapse"></td>
        <td valign="middle" style="border-collapse:collapse"><a href="http://mdiss.createsend3.com/t/j-tw-ftjihl-l-q/" style="font-weight:bold;color:#d9fffd;text-decoration:none" target="_blank"><img src="https://img.createsend1.com/img/templatebuilder/tweet-glyph.png" border="0" width="17" height="13" alt="Twitter icon" style="min-height:auto;line-height:100%;outline-style:none;text-decoration:none;display:block"></a></td>
        <td width="3" style="border-collapse:collapse"></td>
        <td valign="middle" style="border-collapse:collapse"><div style="font-size:12px;color:#d9fffd"><a href="http://mdiss.createsend3.com/t/j-tw-ftjihl-l-a/" style="font-weight:bold;color:#d9fffd;text-decoration:none" target="_blank">Tweet</a></div></td>
        
        
        <td width="10" style="border-collapse:collapse"></td>
        <td valign="middle" style="border-collapse:collapse"><a href="http://mdiss.forwardtomyfriend.com/j-l-2AD73FFF-ftjihl-l-f" style="font-weight:bold;color:#d9fffd;text-decoration:none" target="_blank"><img src="https://img.createsend1.com/img/templatebuilder/forward-glyph.png" border="0" width="19" height="14" alt="Forward icon" style="min-height:auto;line-height:100%;outline-style:none;text-decoration:none;display:block"></a></td>
        <td width="3" style="border-collapse:collapse"></td>
        <td valign="middle" style="border-collapse:collapse"><div style="font-size:12px;color:#d9fffd"><a href="http://mdiss.forwardtomyfriend.com/j-l-2AD73FFF-ftjihl-l-z" style="font-weight:bold;color:#d9fffd;text-decoration:none" target="_blank">Forward</a></div></td>
        
    </tr>
</tbody></table>
            <table width="255" cellpadding="0" cellspacing="0" border="0">
                <tbody><tr style="border-collapse:collapse"><td width="255" height="8" style="border-collapse:collapse"></td></tr>
            </tbody></table>
        </td>
        <td width="15" style="border-collapse:collapse"></td>
    </tr>
</tbody></table>
                        
                    </td>
                </tr>
                <tr style="border-collapse:collapse">
                <td width="640" align="center" bgcolor="#425470" style="border-collapse:collapse">
    
    <table width="640" cellpadding="0" cellspacing="0" border="0">
        <tbody><tr style="border-collapse:collapse"><td width="30" style="border-collapse:collapse"></td><td width="580" height="30" style="border-collapse:collapse"></td><td width="30" style="border-collapse:collapse"></td></tr>
        <tr style="border-collapse:collapse">
            <td width="30" style="border-collapse:collapse"></td>
            <td width="580" style="border-collapse:collapse"><div align="center"><p style="color:#d9fffd;font-family:Helvetica Neue,Arial,Helvetica,Geneva,sans-serif;font-size:36px;text-align:center;margin-top:0px;margin-bottom:30px"><strong>MDISS Photo</strong></p></div></td>
            <td width="30" style="border-collapse:collapse"></td>
        </tr>
    </tbody></table>
    
    
</td>
                </tr>
                
                <tr style="border-collapse:collapse"><td width="640" height="30" bgcolor="#ffffff" style="border-collapse:collapse"></td></tr>
                <tr style="border-collapse:collapse"><td width="640" bgcolor="#ffffff" style="border-collapse:collapse">
    <table width="640" cellpadding="0" cellspacing="0" border="0">
        <tbody><tr style="border-collapse:collapse">
            <td width="30" style="border-collapse:collapse"></td>
            <td width="580" style="border-collapse:collapse">
                
                        <table width="580" cellpadding="0" cellspacing="0" border="0">
                            <tbody><tr style="border-collapse:collapse">
                                <td width="580" style="border-collapse:collapse">
                                    <p align="left" style="font-size:18px;line-height:24px;color:#c25130;font-weight:bold;margin-top:0px;margin-bottom:18px;font-family:Helvetica Neue,Arial,Helvetica,Geneva,sans-serif">New reported photo</p>
                                    <div align="left" style="font-size:13px;line-height:18px;color:#444444;margin-top:0px;margin-bottom:18px;font-family:Helvetica Neue,Arial,Helvetica,Geneva,sans-serif">
                                        <p style="margin-bottom:15px">The user with username $username$ reported the photo with id $photoId$. Please check it.</p>
                                    </div>
                                </td>
                            </tr>
                            <tr style="border-collapse:collapse"><td width="580" height="10" style="border-collapse:collapse"></td></tr>
                        </tbody></table>
                    
            </td>
            <td width="30" style="border-collapse:collapse"></td>
        </tr>
    </tbody></table>
</td></tr>
                <tr style="border-collapse:collapse"><td width="640" height="15" bgcolor="#ffffff" style="border-collapse:collapse"></td></tr>
                
                <tr style="border-collapse:collapse">
                <td width="640" style="border-collapse:collapse">
    <table width="640" cellpadding="0" cellspacing="0" border="0" bgcolor="#425470" style="border-radius:0px 0px 6px 6px;background-color:#425470;color:#d9fffd">
    <tbody><tr style="border-collapse:collapse"><td width="30" style="border-collapse:collapse"></td><td width="360" height="30" style="border-collapse:collapse"></td><td width="60" style="border-collapse:collapse"></td><td width="160" style="border-collapse:collapse"></td><td width="30" style="border-collapse:collapse"></td></tr>
        <tr style="border-collapse:collapse">
            <td width="30" style="border-collapse:collapse"></td>
            <td width="360" valign="top" style="border-collapse:collapse">
	            <!--  <span>-->
	            <p align="left" style="font-size:12px;line-height:15px;color:#d9fffd;margin-top:0px;margin-bottom:15px;white-space:normal">
	            	<span>You're receiving this because you registered in MDISS Photo</span>
	            </p>
	            <!-- </span> -->
	            <p align="left" style="font-size:12px;line-height:15px;color:#d9fffd;margin-top:0px;margin-bottom:15px"><a href="http://mdiss.updatemyprofile.com/j-l-2AD73FFF-l-v" style="color:#d9fffd;text-decoration:none;font-weight:bold" target="_blank">Edit your subscription</a> | <a href="http://mdiss.createsend3.com/t/j-u-ftjihl-l-e/" style="color:#d9fffd;text-decoration:none;font-weight:bold" target="_blank">Unsubscribe instantly</a></p>
            </td>
            <td width="60" style="border-collapse:collapse"></td>
            <td width="160" valign="top" style="border-collapse:collapse">
            	<p align="right" style="font-size:11px;line-height:16px;margin-top:0px;margin-bottom:15px;color:#d9fffd;white-space:normal"></p>
            </td>
            <td width="30" style="border-collapse:collapse"></td>
        </tr>
        <tr style="border-collapse:collapse"><td width="30" style="border-collapse:collapse"></td><td width="360" height="15" style="border-collapse:collapse"></td><td width="60" style="border-collapse:collapse"></td><td width="160" style="border-collapse:collapse"></td><td width="30" style="border-collapse:collapse"></td></tr>
    </tbody></table>
</td>
                </tr>
                <tr style="border-collapse:collapse"><td width="640" height="60" style="border-collapse:collapse"></td></tr>
            </tbody></table>
        </td>
	</tr>
</tbody>
</table>
</body>
</head>
>>

